In [29]:
import pandas as pd
import numpy as np

In [30]:
TEST_Data_cae_ue_folder='../Data_cae_ue/ANOVA_Kruskal_test/'
TEST_Data_edo_cae_folder='../Data_edo_cae/ANOVA_Kruskal_test/'
TEST_Data_pot_cae_folder='../Data_pot/ANOVA_Kruskal_test/'

In [31]:
df_Data_cae_ue_04_09=pd.read_csv(TEST_Data_cae_ue_folder+'ANOVA_Kruskal_test_04_09.csv',index_col=0)
df_Data_cae_ue_09_14=pd.read_csv(TEST_Data_cae_ue_folder+'ANOVA_Kruskal_test_09_14.csv',index_col=0)
df_Data_cae_ue_14_19=pd.read_csv(TEST_Data_cae_ue_folder+'ANOVA_Kruskal_test_14_19.csv',index_col=0)

df_Data_edo_cae_04_09=pd.read_csv(TEST_Data_edo_cae_folder+'ANOVA_Kruskal_test_04_09.csv',index_col=0)
df_Data_edo_cae_09_14=pd.read_csv(TEST_Data_edo_cae_folder+'ANOVA_Kruskal_test_09_14.csv',index_col=0)
df_Data_edo_cae_14_19=pd.read_csv(TEST_Data_edo_cae_folder+'ANOVA_Kruskal_test_14_19.csv',index_col=0)

df_Data_pot_cae_04_09=pd.read_csv(TEST_Data_pot_cae_folder+'ANOVA_Kruskal_test_04_09.csv',index_col=0)
df_Data_pot_cae_09_14=pd.read_csv(TEST_Data_pot_cae_folder+'ANOVA_Kruskal_test_09_14.csv',index_col=0)
df_Data_pot_cae_14_19=pd.read_csv(TEST_Data_pot_cae_folder+'ANOVA_Kruskal_test_14_19.csv',index_col=0)

In [32]:
df_Data_cae_ue_04_09_0_ANOVA=df_Data_cae_ue_04_09[df_Data_cae_ue_04_09['ANOVA_flag']==0]
df_Data_cae_ue_04_09_0_ANOVA['Data_set']='Data_cae_ue'
df_Data_cae_ue_09_14_0_ANOVA=df_Data_cae_ue_09_14[df_Data_cae_ue_09_14['ANOVA_flag']==0]
df_Data_cae_ue_09_14_0_ANOVA['Data_set']='Data_cae_ue'
df_Data_cae_ue_14_19_0_ANOVA=df_Data_cae_ue_14_19[df_Data_cae_ue_14_19['ANOVA_flag']==0]
df_Data_cae_ue_14_19_0_ANOVA['Data_set']='Data_cae_ue'

df_Data_cae_ue_ALL_0_ANOVA=pd.concat([df_Data_cae_ue_04_09_0_ANOVA,df_Data_cae_ue_09_14_0_ANOVA,df_Data_cae_ue_14_19_0_ANOVA])

import os

directory_name = "CSVs"

# Check if the directory exists
if not os.path.exists(directory_name):
    # Create the directory
    os.makedirs(directory_name)
    print(f"Directory '{directory_name}' created successfully.")
else:
    print(f"Directory '{directory_name}' already exists.")


df_Data_cae_ue_ALL_0_ANOVA.to_csv('CSVs/Data_cae_ue_ALL_0_ANOVA.csv')

df_Data_cae_ue_ALL_0_ANOVA

Directory 'CSVs' already exists.

C:\Users\L03537813\AppData\Local\Temp\ipykernel_23028\1311923671.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_Data_cae_ue_04_09_0_ANOVA['Data_set']='Data_cae_ue'
C:\Users\L03537813\AppData\Local\Temp\ipykernel_23028\1311923671.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_Data_cae_ue_09_14_0_ANOVA['Data_set']='Data_cae_ue'
C:\Users\L03537813\AppData\Local\Temp\ipykernel_23028\1311923671.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_Data_cae_ue_14_19_0_ANOVA['Data_set']='Data_cae_ue'

              Estado    Periodo  ANOVA_flag  Kruskal_flag     Data_set
4           Coahuila  2004-2009           0             0  Data_cae_ue
6            Chiapas  2004-2009           0             0  Data_cae_ue
10        Guanajuato  2004-2009           0             0  Data_cae_ue
13           Jalisco  2004-2009           0             0  Data_cae_ue
15         Michoacán  2004-2009           0             0  Data_cae_ue
16           Morelos  2004-2009           0             0  Data_cae_ue
20            Puebla  2004-2009           0             0  Data_cae_ue
29          Veracruz  2004-2009           0             0  Data_cae_ue
30           Yucatán  2004-2009           0             0  Data_cae_ue
8   Ciudad de México  2009-2014           0             0  Data_cae_ue
10        Guanajuato  2009-2014           0             1  Data_cae_ue
14            México  2009-2014           0             0  Data_cae_ue
15         Michoacán  2009-2014           0             0  Data_cae_ue
16           Morelos  2009-2014           0             0  Data_cae_ue
18        Nuevo León  2009-2014           0             1  Data_cae_ue
20            Puebla  2009-2014           0             0  Data_cae_ue
25            Sonora  2009-2014           0             0  Data_cae_ue
28          Tlaxcala  2009-2014           0             0  Data_cae_ue
29          Veracruz  2009-2014           0             0  Data_cae_ue
30           Yucatán  2009-2014           0             0  Data_cae_ue
8   Ciudad de México  2014-2019           0             0  Data_cae_ue
10        Guanajuato  2014-2019           0             0  Data_cae_ue
11          Guerrero  2014-2019           0             1  Data_cae_ue
12           Hidalgo  2014-2019           0             0  Data_cae_ue
15         Michoacán  2014-2019           0             0  Data_cae_ue
16           Morelos  2014-2019           0             0  Data_cae_ue
20            Puebla  2014-2019           0             0  Data_cae_ue
26           Tabasco  2014-2019           0             1  Data_cae_ue
30           Yucatán  2014-2019           0             0  Data_cae_ue
31         Zacatecas  2014-2019           0             0  Data_cae_ue

In [33]:
df_common_states_Data_cae_ue_ANOVA = df_Data_cae_ue_04_09_0_ANOVA.merge(df_Data_cae_ue_09_14_0_ANOVA, on='Estado', how='inner')
df_common_states_Data_cae_ue_ANOVA = df_common_states_Data_cae_ue_ANOVA.merge(df_Data_cae_ue_14_19_0_ANOVA, on='Estado', how='inner')

df_common_states_Data_cae_ue_ANOVA=df_common_states_Data_cae_ue_ANOVA[['Estado','ANOVA_flag','Kruskal_flag','Data_set']]

df_common_states_Data_cae_ue_ANOVA.to_csv('CSVs/common_states_Data_cae_ue_ANOVA.csv')

df_common_states_Data_cae_ue_ANOVA

       Estado  ANOVA_flag  Kruskal_flag     Data_set
0  Guanajuato           0             0  Data_cae_ue
1   Michoacán           0             0  Data_cae_ue
2     Morelos           0             0  Data_cae_ue
3      Puebla           0             0  Data_cae_ue
4     Yucatán           0             0  Data_cae_ue

In [34]:
df_Data_cae_ue_04_09_0_Kruskal=df_Data_cae_ue_04_09[df_Data_cae_ue_04_09['Kruskal_flag']==0]
df_Data_cae_ue_04_09_0_Kruskal['Data_set']='Data_cae_ue'
df_Data_cae_ue_09_14_0_Kruskal=df_Data_cae_ue_09_14[df_Data_cae_ue_09_14['Kruskal_flag']==0]
df_Data_cae_ue_09_14_0_Kruskal['Data_set']='Data_cae_ue'
df_Data_cae_ue_14_19_0_Kruskal=df_Data_cae_ue_14_19[df_Data_cae_ue_14_19['Kruskal_flag']==0]
df_Data_cae_ue_14_19_0_Kruskal['Data_set']='Data_cae_ue'

df_Data_cae_ue_ALL_0_Kruskal=pd.concat([df_Data_cae_ue_04_09_0_Kruskal,
                                        df_Data_cae_ue_09_14_0_Kruskal,
                                        df_Data_cae_ue_14_19_0_Kruskal])

df_Data_cae_ue_ALL_0_Kruskal.to_csv('CSVs/Data_cae_ue_ALL_0_Kruskal.csv')


df_Data_cae_ue_ALL_0_Kruskal

C:\Users\L03537813\AppData\Local\Temp\ipykernel_23028\4036855378.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_Data_cae_ue_04_09_0_Kruskal['Data_set']='Data_cae_ue'
C:\Users\L03537813\AppData\Local\Temp\ipykernel_23028\4036855378.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_Data_cae_ue_09_14_0_Kruskal['Data_set']='Data_cae_ue'
C:\Users\L03537813\AppData\Local\Temp\ipykernel_23028\4036855378.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_Data_cae_ue_14_19_0_Kruskal['Data_set']='Data_cae_ue'

              Estado    Periodo  ANOVA_flag  Kruskal_flag     Data_set
4           Coahuila  2004-2009           0             0  Data_cae_ue
6            Chiapas  2004-2009           0             0  Data_cae_ue
10        Guanajuato  2004-2009           0             0  Data_cae_ue
12           Hidalgo  2004-2009           1             0  Data_cae_ue
13           Jalisco  2004-2009           0             0  Data_cae_ue
15         Michoacán  2004-2009           0             0  Data_cae_ue
16           Morelos  2004-2009           0             0  Data_cae_ue
20            Puebla  2004-2009           0             0  Data_cae_ue
29          Veracruz  2004-2009           0             0  Data_cae_ue
30           Yucatán  2004-2009           0             0  Data_cae_ue
8   Ciudad de México  2009-2014           0             0  Data_cae_ue
14            México  2009-2014           0             0  Data_cae_ue
15         Michoacán  2009-2014           0             0  Data_cae_ue
16           Morelos  2009-2014           0             0  Data_cae_ue
20            Puebla  2009-2014           0             0  Data_cae_ue
25            Sonora  2009-2014           0             0  Data_cae_ue
28          Tlaxcala  2009-2014           0             0  Data_cae_ue
29          Veracruz  2009-2014           0             0  Data_cae_ue
30           Yucatán  2009-2014           0             0  Data_cae_ue
3           Campeche  2014-2019           1             0  Data_cae_ue
8   Ciudad de México  2014-2019           0             0  Data_cae_ue
10        Guanajuato  2014-2019           0             0  Data_cae_ue
12           Hidalgo  2014-2019           0             0  Data_cae_ue
15         Michoacán  2014-2019           0             0  Data_cae_ue
16           Morelos  2014-2019           0             0  Data_cae_ue
20            Puebla  2014-2019           0             0  Data_cae_ue
27        Tamaulipas  2014-2019           1             0  Data_cae_ue
28          Tlaxcala  2014-2019           1             0  Data_cae_ue
30           Yucatán  2014-2019           0             0  Data_cae_ue
31         Zacatecas  2014-2019           0             0  Data_cae_ue

In [35]:
df_common_states_Data_cae_ue_Kruskal = df_Data_cae_ue_04_09_0_Kruskal.merge(df_Data_cae_ue_09_14_0_Kruskal, on='Estado', how='inner')
df_common_states_Data_cae_ue_Kruskal = df_common_states_Data_cae_ue_Kruskal.merge(df_Data_cae_ue_14_19_0_Kruskal, on='Estado', how='inner')

df_common_states_Data_cae_ue_Kruskal=df_common_states_Data_cae_ue_Kruskal[['Estado','ANOVA_flag','Kruskal_flag','Data_set']]

df_common_states_Data_cae_ue_Kruskal.to_csv('CSVs/common_states_Data_cae_ue_Kruskal.csv')

df_common_states_Data_cae_ue_Kruskal

      Estado  ANOVA_flag  Kruskal_flag     Data_set
0  Michoacán           0             0  Data_cae_ue
1    Morelos           0             0  Data_cae_ue
2     Puebla           0             0  Data_cae_ue
3    Yucatán           0             0  Data_cae_ue

In [36]:
df_Data_edo_cae_04_09_0_ANOVA=df_Data_edo_cae_04_09[df_Data_edo_cae_04_09['ANOVA_flag']==0]
df_Data_edo_cae_04_09_0_ANOVA['Data_set']='Data_edo_cae'
df_Data_edo_cae_09_14_0_ANOVA=df_Data_edo_cae_09_14[df_Data_edo_cae_09_14['ANOVA_flag']==0]
df_Data_edo_cae_09_14_0_ANOVA['Data_set']='Data_edo_cae'
df_Data_edo_cae_14_19_0_ANOVA=df_Data_edo_cae_14_19[df_Data_edo_cae_14_19['ANOVA_flag']==0]
df_Data_edo_cae_14_19_0_ANOVA['Data_set']='Data_edo_cae'

df_Data_edo_cae_ALL_0_ANOVA=pd.concat([df_Data_edo_cae_04_09_0_ANOVA,
                                       df_Data_edo_cae_09_14_0_ANOVA,
                                       df_Data_edo_cae_14_19_0_ANOVA])

df_Data_edo_cae_ALL_0_ANOVA.to_csv('CSVs/Data_edo_cae_ALL_0_ANOVA.csv')



df_Data_edo_cae_ALL_0_ANOVA

C:\Users\L03537813\AppData\Local\Temp\ipykernel_23028\2616197379.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_Data_edo_cae_04_09_0_ANOVA['Data_set']='Data_edo_cae'
C:\Users\L03537813\AppData\Local\Temp\ipykernel_23028\2616197379.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_Data_edo_cae_14_19_0_ANOVA['Data_set']='Data_edo_cae'

             Estado    Periodo  ANOVA_flag  Kruskal_flag      Data_set
4          Coahuila  2004-2009           0             0  Data_edo_cae
10       Guanajuato  2004-2009           0             0  Data_edo_cae
12          Hidalgo  2004-2009           0             1  Data_edo_cae
13          Jalisco  2004-2009           0             0  Data_edo_cae
18       Nuevo León  2004-2009           0             0  Data_edo_cae
27       Tamaulipas  2004-2009           0             0  Data_edo_cae
10       Guanajuato  2014-2019           0             0  Data_edo_cae
13          Jalisco  2014-2019           0             0  Data_edo_cae
20           Puebla  2014-2019           0             0  Data_edo_cae
23  San Luis Potosí  2014-2019           0             0  Data_edo_cae
30          Yucatán  2014-2019           0             0  Data_edo_cae

In [37]:
df_Data_edo_cae_04_09_0_Kruskal=df_Data_edo_cae_04_09[df_Data_edo_cae_04_09['Kruskal_flag']==0]
df_Data_edo_cae_04_09_0_Kruskal['Data_set']='Data_edo_cae'
df_Data_edo_cae_09_14_0_Kruskal=df_Data_edo_cae_09_14[df_Data_edo_cae_09_14['Kruskal_flag']==0]
df_Data_edo_cae_09_14_0_Kruskal['Data_set']='Data_edo_cae'
df_Data_edo_cae_14_19_0_Kruskal=df_Data_edo_cae_14_19[df_Data_edo_cae_14_19['Kruskal_flag']==0]
df_Data_edo_cae_14_19_0_Kruskal['Data_set']='Data_edo_cae'

df_Data_edo_cae_ALL_0_Kruskal=pd.concat([df_Data_edo_cae_04_09_0_Kruskal,
                                       df_Data_edo_cae_09_14_0_Kruskal,
                                       df_Data_edo_cae_14_19_0_Kruskal])

df_Data_edo_cae_ALL_0_Kruskal.to_csv('CSVs/Data_edo_cae_ALL_0_Kruskal.csv')


df_Data_edo_cae_ALL_0_Kruskal

C:\Users\L03537813\AppData\Local\Temp\ipykernel_23028\2008930574.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_Data_edo_cae_04_09_0_Kruskal['Data_set']='Data_edo_cae'
C:\Users\L03537813\AppData\Local\Temp\ipykernel_23028\2008930574.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_Data_edo_cae_14_19_0_Kruskal['Data_set']='Data_edo_cae'

             Estado    Periodo  ANOVA_flag  Kruskal_flag      Data_set
4          Coahuila  2004-2009           0             0  Data_edo_cae
10       Guanajuato  2004-2009           0             0  Data_edo_cae
13          Jalisco  2004-2009           0             0  Data_edo_cae
18       Nuevo León  2004-2009           0             0  Data_edo_cae
27       Tamaulipas  2004-2009           0             0  Data_edo_cae
10       Guanajuato  2014-2019           0             0  Data_edo_cae
13          Jalisco  2014-2019           0             0  Data_edo_cae
20           Puebla  2014-2019           0             0  Data_edo_cae
23  San Luis Potosí  2014-2019           0             0  Data_edo_cae
30          Yucatán  2014-2019           0             0  Data_edo_cae

In [38]:
df_Data_pot_cae_04_09_0_ANOVA=df_Data_pot_cae_04_09[df_Data_pot_cae_04_09['ANOVA_flag']==0]
df_Data_pot_cae_04_09_0_ANOVA['Data_set']='Data_pot_cae'
df_Data_pot_cae_09_14_0_ANOVA=df_Data_pot_cae_09_14[df_Data_pot_cae_09_14['ANOVA_flag']==0]
df_Data_pot_cae_09_14_0_ANOVA['Data_set']='Data_pot_cae'
df_Data_pot_cae_14_19_0_ANOVA=df_Data_pot_cae_14_19[df_Data_pot_cae_14_19['ANOVA_flag']==0]
df_Data_pot_cae_14_19_0_ANOVA['Data_set']='Data_pot_cae'

df_Data_pot_cae_ALL_0_ANOVA=pd.concat([df_Data_pot_cae_04_09_0_ANOVA,
                                       df_Data_pot_cae_09_14_0_ANOVA,
                                       df_Data_pot_cae_14_19_0_ANOVA])

df_Data_pot_cae_ALL_0_ANOVA.to_csv('CSVs/Data_pot_cae_ALL_0_ANOVA.csv')


df_Data_pot_cae_ALL_0_ANOVA

C:\Users\L03537813\AppData\Local\Temp\ipykernel_23028\1533020037.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_Data_pot_cae_04_09_0_ANOVA['Data_set']='Data_pot_cae'
C:\Users\L03537813\AppData\Local\Temp\ipykernel_23028\1533020037.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_Data_pot_cae_09_14_0_ANOVA['Data_set']='Data_pot_cae'
C:\Users\L03537813\AppData\Local\Temp\ipykernel_23028\1533020037.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_Data_pot_cae_14_19_0_ANOVA['Data_set']='Data_pot_cae'

              Estado    Periodo  ANOVA_flag  Kruskal_flag      Data_set
1    Baja California  2004-2009           0             0  Data_pot_cae
8   Ciudad de México  2004-2009           0             0  Data_pot_cae
14            México  2004-2009           0             0  Data_pot_cae
18        Nuevo León  2004-2009           0             1  Data_pot_cae
21         Querétaro  2004-2009           0             0  Data_pot_cae
23   San Luis Potosí  2004-2009           0             0  Data_pot_cae
28          Tlaxcala  2004-2009           0             0  Data_pot_cae
14            México  2009-2014           0             0  Data_pot_cae
15         Michoacán  2009-2014           0             0  Data_pot_cae
20            Puebla  2009-2014           0             0  Data_pot_cae
1    Baja California  2014-2019           0             0  Data_pot_cae
8   Ciudad de México  2014-2019           0             0  Data_pot_cae
13           Jalisco  2014-2019           0             0  Data_pot_cae
14            México  2014-2019           0             0  Data_pot_cae
15         Michoacán  2014-2019           0             0  Data_pot_cae
18        Nuevo León  2014-2019           0             1  Data_pot_cae
20            Puebla  2014-2019           0             0  Data_pot_cae
21         Querétaro  2014-2019           0             0  Data_pot_cae
24           Sinaloa  2014-2019           0             0  Data_pot_cae
28          Tlaxcala  2014-2019           0             0  Data_pot_cae

In [39]:
df_common_states_Data_pot_cae_ANOVA = df_Data_pot_cae_04_09_0_ANOVA.merge(df_Data_pot_cae_09_14_0_ANOVA, on='Estado', how='inner')
df_common_states_Data_pot_cae_ANOVA = df_common_states_Data_pot_cae_ANOVA.merge(df_Data_pot_cae_14_19_0_ANOVA, on='Estado', how='inner')

df_common_states_Data_pot_cae_ANOVA=df_common_states_Data_pot_cae_ANOVA[['Estado','ANOVA_flag','Kruskal_flag','Data_set']]

df_common_states_Data_pot_cae_ANOVA.to_csv('CSVs/common_states_Data_pot_cae_ANOVA.csv')

df_common_states_Data_pot_cae_ANOVA

   Estado  ANOVA_flag  Kruskal_flag      Data_set
0  México           0             0  Data_pot_cae

In [40]:
df_Data_pot_cae_04_09_0_Kruskal=df_Data_pot_cae_04_09[df_Data_pot_cae_04_09['Kruskal_flag']==0]
df_Data_pot_cae_04_09_0_Kruskal['Data_set']='Data_pot_cae'
df_Data_pot_cae_09_14_0_Kruskal=df_Data_pot_cae_09_14[df_Data_pot_cae_09_14['Kruskal_flag']==0]
df_Data_pot_cae_09_14_0_Kruskal['Data_set']='Data_pot_cae'
df_Data_pot_cae_14_19_0_Kruskal=df_Data_pot_cae_14_19[df_Data_pot_cae_14_19['Kruskal_flag']==0]
df_Data_pot_cae_14_19_0_Kruskal['Data_set']='Data_pot_cae'

df_Data_pot_cae_ALL_0_Kruskal=pd.concat([df_Data_pot_cae_04_09_0_Kruskal,
                                       df_Data_pot_cae_09_14_0_Kruskal,
                                       df_Data_pot_cae_14_19_0_Kruskal])

df_Data_pot_cae_ALL_0_Kruskal.to_csv('CSVs/Data_pot_cae_ALL_0_Kruskal.csv')


df_Data_pot_cae_ALL_0_Kruskal

C:\Users\L03537813\AppData\Local\Temp\ipykernel_23028\4008699930.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_Data_pot_cae_04_09_0_Kruskal['Data_set']='Data_pot_cae'
C:\Users\L03537813\AppData\Local\Temp\ipykernel_23028\4008699930.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_Data_pot_cae_09_14_0_Kruskal['Data_set']='Data_pot_cae'
C:\Users\L03537813\AppData\Local\Temp\ipykernel_23028\4008699930.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_Data_pot_cae_14_19_0_Kruskal['Data_set']='Data_pot_cae'

              Estado    Periodo  ANOVA_flag  Kruskal_flag      Data_set
1    Baja California  2004-2009           0             0  Data_pot_cae
8   Ciudad de México  2004-2009           0             0  Data_pot_cae
10        Guanajuato  2004-2009           1             0  Data_pot_cae
13           Jalisco  2004-2009           1             0  Data_pot_cae
14            México  2004-2009           0             0  Data_pot_cae
21         Querétaro  2004-2009           0             0  Data_pot_cae
22      Quintana Roo  2004-2009           1             0  Data_pot_cae
23   San Luis Potosí  2004-2009           0             0  Data_pot_cae
28          Tlaxcala  2004-2009           0             0  Data_pot_cae
13           Jalisco  2009-2014           1             0  Data_pot_cae
14            México  2009-2014           0             0  Data_pot_cae
15         Michoacán  2009-2014           0             0  Data_pot_cae
20            Puebla  2009-2014           0             0  Data_pot_cae
1    Baja California  2014-2019           0             0  Data_pot_cae
8   Ciudad de México  2014-2019           0             0  Data_pot_cae
13           Jalisco  2014-2019           0             0  Data_pot_cae
14            México  2014-2019           0             0  Data_pot_cae
15         Michoacán  2014-2019           0             0  Data_pot_cae
20            Puebla  2014-2019           0             0  Data_pot_cae
21         Querétaro  2014-2019           0             0  Data_pot_cae
24           Sinaloa  2014-2019           0             0  Data_pot_cae
28          Tlaxcala  2014-2019           0             0  Data_pot_cae

In [41]:
df_common_states_Data_pot_cae_Kruskal = df_Data_pot_cae_04_09_0_Kruskal.merge(df_Data_pot_cae_09_14_0_Kruskal, on='Estado', how='inner')
df_common_states_Data_pot_cae_Kruskal = df_common_states_Data_pot_cae_Kruskal.merge(df_Data_pot_cae_14_19_0_Kruskal, on='Estado', how='inner')

df_common_states_Data_pot_cae_Kruskal=df_common_states_Data_pot_cae_Kruskal[['Estado','ANOVA_flag','Kruskal_flag','Data_set']]

df_common_states_Data_pot_cae_Kruskal.to_csv('CSVs/common_states_Data_pot_cae_Kruskal.csv')

df_common_states_Data_pot_cae_Kruskal

    Estado  ANOVA_flag  Kruskal_flag      Data_set
0  Jalisco           0             0  Data_pot_cae
1   México           0             0  Data_pot_cae